name: Create Release

on:
  push:
    branches: main
    paths:
      - '**/*.py'
      - requirements.txt

permissions:
  contents: write

jobs:
  Release:
    uses: THD-C/GH_Actions/.github/workflows/release.yml@main